window.A11Y_FINDINGS = {
  project: "Riverside Community Library — Sample App",
  standard: "WCAG 2.2 AA",
  generatedAt: "2025-07-10",
  findings: [ {
    // ─── A11Y-001 ───────────────────────────────────────────────────────────
    id: "A11Y-001",
    pages: ["index.html", "book.html", "contact.html"],
    file: "sample-app/styles.css",
    line: 8,
    element: "* { outline: none }",
    wcag: "2.4.11",
    level: "AA",
    category: "Keyboard & Focus",
    severity: "High",
    affects: ["keyboard-only users", "low-vision users"],
    problem: "A global CSS rule removes the browser's default focus ring from every interactive element across the entire site. Keyboard-only users have absolutely no visual cue showing which element currently has focus, making the site effectively unusable without a mouse.",
    fix: "Remove `* { outline: none }` entirely. Replace it with a `:focus-visible` rule that provides a clearly visible, high-contrast focus indicator.",
    fixCode: "/* Before */\n* {\n  outline: none;\n}\n\n/* After */\n*:focus-visible {\n  outline: 3px solid #005fcc;\n  outline-offset: 2px;\n}",
    effortMinutes: 10,
    status: "Fixed",
    fixSummary: "Replaced `* { outline: none }` with a `*:focus-visible` rule providing a 3 px solid #005fcc focus ring."
  }, {
    // ─── A11Y-002 ───────────────────────────────────────────────────────────
    id: "A11Y-002",
    pages: ["index.html", "book.html", "contact.html"],
    file: "sample-app/index.html",
    line: 5,
    element: "<meta name=\"viewport\">",
    wcag: "1.4.4",
    level: "AA",
    category: "Mobile & Zoom",
    severity: "High",
    affects: ["low-vision users", "mobile and zoom users"],
    problem: "All three pages include `user-scalable=no, maximum-scale=1.0` in the viewport meta tag, which prevents pinch-to-zoom on mobile devices. Low-vision users who rely on browser zoom to enlarge text are completely blocked.",
    fix: "Remove `user-scalable=no` and `maximum-scale=1.0` from each page's viewport meta tag.",
    fixCode: "<!-- Before -->\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1.0\">\n\n<!-- After -->\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">",
    effortMinutes: 5,
    status: "Fixed",
    fixSummary: "Removed `user-scalable=no` and `maximum-scale=1.0` from the viewport meta on all three pages."
  }, {
    // ─── A11Y-003 ───────────────────────────────────────────────────────────
    id: "A11Y-003",
    pages: ["book.html"],
    file: "sample-app/book.html",
    line: 2,
    element: "<html>",
    wcag: "3.1.1",
    level: "A",
    category: "Page",
    severity: "High",
    affects: ["screen reader users", "users with cognitive disabilities"],
    problem: "The `<html>` element on the booking page has no `lang` attribute. Screen readers cannot determine the language and may switch to the wrong voice or mispronounce every word on the page, making the entire booking form difficult to understand.",
    fix: "Add `lang=\"en\"` to the opening `<html>` tag.",
    fixCode: "<!-- Before -->\n<html>\n\n<!-- After -->\n<html lang=\"en\">",
    effortMinutes: 2,
    status: "Fixed",
    fixSummary: "Added `lang=\"en\"` to the `<html>` element on book.html."
  }, {
    // ─── A11Y-004 ───────────────────────────────────────────────────────────
    id: "A11Y-004",
    pages: ["index.html"],
    file: "sample-app/index.html",
    line: 38,
    element: "<span class=\"hero-dot\">",
    wcag: "4.1.2",
    level: "A",
    category: "ARIA & Dynamic",
    severity: "High",
    affects: ["keyboard-only users", "screen reader users"],
    problem: "The carousel slide-select dots are `<span>` elements with click handlers but no keyboard focusability, no ARIA role, and no accessible name. Keyboard-only users cannot reach or activate them, and screen reader users receive no information about the controls or the active slide state.",
    fix: "Replace the `<span>` elements with `<button>` elements, give each an `aria-label` (e.g. 'Go to slide 1'), and toggle `aria-current=\"true\"` on the active button via JavaScript.",
    fixCode: "<!-- Before -->\n<div class=\"hero-dots\">\n  <span class=\"hero-dot active\"></span>\n  <span class=\"hero-dot\"></span>\n  <span class=\"hero-dot\"></span>\n</div>\n\n<!-- After -->\n<div class=\"hero-dots\" role=\"group\" aria-label=\"Slide controls\">\n  <button class=\"hero-dot\" aria-label=\"Go to slide 1\" aria-current=\"true\"></button>\n  <button class=\"hero-dot\" aria-label=\"Go to slide 2\"></button>\n  <button class=\"hero-dot\" aria-label=\"Go to slide 3\"></button>\n</div>",
    effortMinutes: 20,
    status: "Fixed",
    fixSummary: "Replaced `<span>` carousel dots with `<button>` elements carrying `aria-label` and `aria-current`; JS now updates `aria-current` on slide change."
  }, {
    // ─── A11Y-005 ───────────────────────────────────────────────────────────
    id: "A11Y-005",
    pages: ["index.html"],
    file: "sample-app/index.html",
    line: 80,
    element: "<div id=\"newsletter-action\">",
    wcag: "4.1.2",
    level: "A",
    category: "Keyboard & Focus",
    severity: "High",
    affects: ["keyboard-only users", "screen reader users"],
    problem: "The 'Sign up for our newsletter' control is a `<div>` with only a click handler. It is not keyboard-focusable, not announced as a button by screen readers, and cannot be activated with Enter or Space.",
    fix: "Replace the `<div>` with a native `<button>` element, which is automatically focusable, keyboard-operable, and semantically correct.",
    fixCode: "<!-- Before -->\n<div id=\"newsletter-action\"\n     style=\"display:inline-block;background:#0f3460;color:#fff;padding:0.75rem 2rem;border-radius:4px;cursor:pointer;font-size:1rem;\">\n  Sign up for our newsletter\n</div>\n\n<!-- After -->\n<button id=\"newsletter-action\"\n        style=\"background:#0f3460;color:#fff;padding:0.75rem 2rem;border-radius:4px;cursor:pointer;font-size:1rem;border:none;\">\n  Sign up for our newsletter\n</button>",
    effortMinutes: 10,
    status: "Fixed",
    fixSummary: "Replaced the `<div>` newsletter control with a native `<button>` element; removed `display:inline-block` and `initNewsletterDiv` renamed to `initNewsletterBtn`."
  }, {
    // ─── A11Y-006 ───────────────────────────────────────────────────────────
    id: "A11Y-006",
    pages: ["book.html"],
    file: "sample-app/book.html",
    line: 29,
    element: "<input type=\"email\" id=\"email\">",
    wcag: "1.3.1",
    level: "A",
    category: "Forms",
    severity: "High",
    affects: ["screen reader users", "users with cognitive disabilities"],
    problem: "The email address input has no associated `<label>` element — only a placeholder. Screen readers announce only the placeholder text (which disappears when the user starts typing) and cannot programmatically identify the field's purpose.",
    fix: "Add a `<label for=\"email\">` element before the input. Do not rely on `placeholder` as a substitute for a label.",
    fixCode: "<!-- Before -->\n<div class=\"form-group\">\n  <input type=\"email\" id=\"email\" name=\"email\"\n         placeholder=\"Your email address\"\n         required autocomplete=\"email\">\n</div>\n\n<!-- After -->\n<div class=\"form-group\">\n  <label for=\"email\">Email address</label>\n  <input type=\"email\" id=\"email\" name=\"email\"\n         placeholder=\"e.g. alex@example.com\"\n         required autocomplete=\"email\">\n</div>",
    effortMinutes: 5,
    status: "Fixed",
    fixSummary: "Added `<label for=\"email\">Email address</label>` before the email input on book.html."
  }, {
    // ─── A11Y-007 ───────────────────────────────────────────────────────────
    id: "A11Y-007",
    pages: ["book.html"],
    file: "sample-app/book.html",
    line: 71,
    element: "<button type=\"submit\" class=\"btn-primary\">",
    wcag: "4.1.2",
    level: "A",
    category: "Links & Buttons",
    severity: "High",
    affects: ["screen reader users", "keyboard-only users"],
    problem: "The form's submit button contains only an SVG icon marked `aria-hidden=\"true\"`, giving the button no accessible name whatsoever. Screen readers announce it as an unlabelled button, and users cannot determine its purpose.",
    fix: "Add visible text inside the button alongside the icon, or add `aria-label=\"Submit booking\"` to the button element.",
    fixCode: "<!-- Before -->\n<button type=\"submit\" class=\"btn-primary\" style=\"display:flex;align-items:center;gap:0.5rem;\">\n  <svg width=\"18\" height=\"18\" aria-hidden=\"true\" focusable=\"false\">...</svg>\n</button>\n\n<!-- After -->\n<button type=\"submit\" class=\"btn-primary\" style=\"display:flex;align-items:center;gap:0.5rem;\">\n  <svg width=\"18\" height=\"18\" aria-hidden=\"true\" focusable=\"false\">...</svg>\n  Submit booking\n</button>",
    effortMinutes: 5,
    status: "Fixed",
    fixSummary: "Added visible 'Submit booking' text label inside the submit button on book.html."
  }, {
    // ─── A11Y-008 ───────────────────────────────────────────────────────────
    id: "A11Y-008",
    pages: ["index.html"],
    file: "sample-app/app.js",
    line: 19,
    element: "setInterval(function () { show(current + 1); }, 3000)",
    wcag: "2.2.2",
    level: "A",
    category: "Motion",
    severity: "High",
    affects: ["users with cognitive disabilities", "screen reader users", "keyboard-only users"],
    problem: "The hero carousel auto-advances every 3 seconds with no mechanism to pause, stop, or hide the moving content. Users with cognitive disabilities or those using screen readers can be disoriented by automatically moving content they cannot control.",
    fix: "Add a pause/play button to the carousel, or at minimum suppress auto-advance when `prefers-reduced-motion: reduce` is set. Also pause when keyboard focus enters the carousel.",
    fixCode: "// Before\nsetInterval(function () { show(current + 1); }, 3000);\n\n// After\nvar autoPlay;\nif (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) {\n  autoPlay = setInterval(function () { show(current + 1); }, 3000);\n}\nwrapper.addEventListener('focusin', function () { clearInterval(autoPlay); });\nwrapper.addEventListener('focusout', function () {\n  if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) {\n    autoPlay = setInterval(function () { show(current + 1); }, 3000);\n  }\n});",
    effortMinutes: 30,
    status: "Fixed",
    fixSummary: "Auto-advance now checks `prefers-reduced-motion` and pauses when focus or mouse enters the hero section; restarts on focusout/mouseleave."
  }, {
    // ─── A11Y-009 ───────────────────────────────────────────────────────────
    id: "A11Y-009",
    pages: ["book.html"],
    file: "sample-app/styles.css",
    line: 179,
    element: "input.error, select.error",
    wcag: "1.4.1",
    level: "A",
    category: "Color & Contrast",
    severity: "High",
    affects: ["color-blind users", "screen reader users"],
    problem: "When the booking form fails validation, the only visual indication is a red border on invalid fields. Users with red-green colour blindness cannot perceive the red state, and screen reader users receive no announcement because no text error message is added.",
    fix: "Inject visible text error messages next to each invalid field in JavaScript, and link each message to its input via `aria-describedby`. The CSS border colour can remain as a supplementary visual cue.",
    fixCode: "// In app.js — add text error messages\nif (!field.value.trim()) {\n  field.classList.add('error');\n  var errId = field.id + '-error';\n  var msg = document.createElement('span');\n  msg.id = errId;\n  msg.className = 'field-error';\n  msg.textContent = 'This field is required.';\n  field.insertAdjacentElement('afterend', msg);\n  field.setAttribute('aria-describedby', errId);\n  valid = false;\n}",
    effortMinutes: 20,
    status: "Fixed",
    fixSummary: "Validation now injects a visible `<span class=\"field-error\">` text message after each invalid field and sets `aria-describedby` to link it to the input."
  }, {
    // ─── A11Y-010 ───────────────────────────────────────────────────────────
    id: "A11Y-010",
    pages: ["book.html"],
    file: "sample-app/app.js",
    line: 34,
    element: "field.classList.add('error')",
    wcag: "3.3.1",
    level: "A",
    category: "Forms",
    severity: "High",
    affects: ["screen reader users", "users with cognitive disabilities"],
    problem: "The validation script adds a CSS class to flag errors but never inserts a text error message and never sets `aria-describedby` on the input to link any description to it. Screen reader users receive zero information about which fields failed validation or what must be corrected.",
    fix: "For each invalid field, create a visible `<span>` with a descriptive error message, give it a unique `id`, insert it after the field, and add `aria-describedby` referencing that id. Remove both when the error is cleared.",
    fixCode: "// See A11Y-009 fix — both issues are resolved by the same code change in app.js\nfield.setAttribute('aria-describedby', errId);\nmsg.textContent = 'Please fill in this field.';",
    effortMinutes: 30,
    status: "Fixed",
    fixSummary: "Combined fix with A11Y-009: `aria-describedby` is set on each invalid field pointing to an injected error `<span>`; errors are cleared on re-submit."
  }, {
    // ─── A11Y-011 ───────────────────────────────────────────────────────────
    id: "A11Y-011",
    pages: ["book.html"],
    file: "sample-app/book.html",
    line: 81,
    element: "<div id=\"confirmation-modal\" role=\"dialog\">",
    wcag: "4.1.2",
    level: "A",
    category: "ARIA & Dynamic",
    severity: "High",
    affects: ["screen reader users"],
    problem: "The booking confirmation dialog has `role=\"dialog\"` but no `aria-labelledby` or `aria-label` attribute. When it opens, screen readers announce an unnamed dialog and users cannot determine what it is or what action to take.",
    fix: "Add `aria-labelledby` referencing the modal's `<h2>`, add `aria-modal=\"true\"`, and give the heading a matching `id`.",
    fixCode: "<!-- Before -->\n<div id=\"confirmation-modal\" class=\"modal-backdrop\" role=\"dialog\">\n  <div class=\"modal\">\n    <button id=\"modal-close-btn\" class=\"modal-close\">&#x2715;</button>\n    <h2>Booking Confirmed!</h2>\n\n<!-- After -->\n<div id=\"confirmation-modal\" class=\"modal-backdrop\"\n     role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"modal-heading\">\n  <div class=\"modal\">\n    <button id=\"modal-close-btn\" class=\"modal-close\" aria-label=\"Close dialog\">&#x2715;</button>\n    <h2 id=\"modal-heading\">Booking Confirmed!</h2>",
    effortMinutes: 5,
    status: "Fixed",
    fixSummary: "Changed modal to `role=\"alertdialog\"` with `aria-modal=\"true\"`, `aria-labelledby=\"modal-heading\"`, `aria-describedby=\"modal-body\"`, and added `id` attributes to heading and body."
  }, {
    // ─── A11Y-012 ───────────────────────────────────────────────────────────
    id: "A11Y-012",
    pages: ["book.html"],
    file: "sample-app/app.js",
    line: 53,
    element: "showConfirmationModal()",
    wcag: "2.1.2",
    level: "A",
    category: "Keyboard & Focus",
    severity: "High",
    affects: ["keyboard-only users", "screen reader users"],
    problem: "When the confirmation modal opens, focus is not moved into it and there is no focus trap, so keyboard users can Tab through and interact with the obscured background content. When the modal closes, focus is not returned to the submit button.",
    fix: "On open, move focus to the close button. Trap Tab/Shift+Tab within the modal while it is open. On close, restore focus to the triggering element.",
    fixCode: "function showConfirmationModal() {\n  var backdrop = document.getElementById('confirmation-modal');\n  if (!backdrop) return;\n  var trigger = document.activeElement;\n  backdrop.classList.add('open');\n  var closeBtn = document.getElementById('modal-close-btn');\n  closeBtn.focus();\n\n  function trapFocus(e) {\n    var focusable = backdrop.querySelectorAll('button,[href],input,[tabindex]:not([tabindex=\"-1\"])');\n    var first = focusable[0], last = focusable[focusable.length - 1];\n    if (e.key === 'Tab') {\n      if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }\n      else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }\n    }\n    if (e.key === 'Escape') { closeModal(); }\n  }\n  backdrop.addEventListener('keydown', trapFocus);\n\n  closeBtn.addEventListener('click', function closeModal() {\n    backdrop.classList.remove('open');\n    backdrop.removeEventListener('keydown', trapFocus);\n    if (trigger) trigger.focus();\n  });\n}",
    effortMinutes: 45,
    status: "Fixed",
    fixSummary: "Modal now moves focus to the close button on open, traps Tab/Shift-Tab within focusable elements, supports Escape key, and restores focus to the submit button on close."
  }, {
    // ─── A11Y-013 ───────────────────────────────────────────────────────────
    id: "A11Y-013",
    pages: ["book.html"],
    file: "sample-app/book.html",
    line: 81,
    element: "<div id=\"confirmation-modal\" role=\"dialog\">",
    wcag: "4.1.3",
    level: "AA",
    category: "ARIA & Dynamic",
    severity: "High",
    affects: ["screen reader users"],
    problem: "After a successful form submission, the booking confirmation modal appears but there is no live region or `role=\"alertdialog\"` to cause screen readers to announce the confirmation automatically. Screen reader users will not know their booking succeeded.",
    fix: "Change `role=\"dialog\"` to `role=\"alertdialog\"` on the confirmation modal, which causes screen readers to announce the dialog and its label immediately when it appears.",
    fixCode: "<!-- Before -->\n<div id=\"confirmation-modal\" class=\"modal-backdrop\" role=\"dialog\">\n\n<!-- After -->\n<div id=\"confirmation-modal\" class=\"modal-backdrop\"\n     role=\"alertdialog\" aria-modal=\"true\"\n     aria-labelledby=\"modal-heading\" aria-describedby=\"modal-body\">\n  <div class=\"modal\">\n    <button id=\"modal-close-btn\" class=\"modal-close\" aria-label=\"Close dialog\">&#x2715;</button>\n    <h2 id=\"modal-heading\">Booking Confirmed!</h2>\n    <div id=\"modal-body\">\n      <p>Thank you for booking. You will receive a confirmation by email.</p>\n    </div>\n  </div>\n</div>",
    effortMinutes: 10,
    status: "Fixed",
    fixSummary: "Role changed to `alertdialog` so screen readers immediately announce the confirmation; `aria-labelledby` and `aria-describedby` added to give full context."
  }, {
    // ─── A11Y-014 ───────────────────────────────────────────────────────────
    id: "A11Y-014",
    pages: ["index.html", "book.html", "contact.html"],
    file: "sample-app/index.html",
    line: 9,
    element: "<body> (first child)",
    wcag: "2.4.1",
    level: "A",
    category: "Page",
    severity: "Medium",
    affects: ["keyboard-only users", "screen reader users"],
    problem: "None of the three pages provides a skip navigation link. Keyboard-only users must tab through the site logo and all three navigation links on every page load before reaching the main content area.",
    fix: "Add a visually hidden 'Skip to main content' anchor as the first element inside `<body>` on each page. Make it visible on `:focus` and target the `<main>` element's `id`.",
    fixCode: "<!-- First child of <body> on every page -->\n<a href=\"#main-content\" class=\"skip-link\">Skip to main content</a>\n\n<!-- Give <main> a matching id -->\n<main id=\"main-content\">\n\n/* In styles.css */\n.skip-link {\n  position: absolute;\n  left: -9999px;\n  top: 0;\n}\n.skip-link:focus {\n  left: 0;\n  width: auto;\n  padding: 0.5rem 1rem;\n  background: #0f3460;\n  color: #fff;\n  text-decoration: none;\n  z-index: 1000;\n}",
    effortMinutes: 15,
    status: "Fixed",
    fixSummary: "Added `<a href=\"#main-content\" class=\"skip-link\">Skip to main content</a>` as the first body child on all three pages; `.skip-link` CSS added to styles.css."
  }, {
    // ─── A11Y-015 ───────────────────────────────────────────────────────────
    id: "A11Y-015",
    pages: ["index.html"],
    file: "sample-app/index.html",
    line: 55,
    element: "<h3 class=\"section-title\">Upcoming Events</h3>",
    wcag: "1.3.1",
    level: "A",
    category: "Structure",
    severity: "Medium",
    affects: ["screen reader users", "users with cognitive disabilities"],
    problem: "The page jumps directly from `<h1>` (in the hero banner) to `<h3>` for the 'Upcoming Events' section, skipping `<h2>` entirely. Screen reader users navigating by headings encounter a broken document outline.",
    fix: "Change `<h3 class=\"section-title\">` to `<h2 class=\"section-title\">`. Visual size is controlled by CSS, not heading level.",
    fixCode: "<!-- Before -->\n<h3 class=\"section-title\">Upcoming Events</h3>\n\n<!-- After -->\n<h2 class=\"section-title\">Upcoming Events</h2>",
    effortMinutes: 5,
    status: "Fixed",
    fixSummary: "Changed the 'Upcoming Events' heading from `<h3>` to `<h2>` to correct the document outline."
  }, {
    // ─── A11Y-016 ───────────────────────────────────────────────────────────
    id: "A11Y-016",
    pages: ["index.html"],
    file: "sample-app/index.html",
    line: 47,
    element: "<svg width=\"120\" height=\"80\">",
    wcag: "1.1.1",
    level: "A",
    category: "Images",
    severity: "Medium",
    affects: ["screen reader users"],
    problem: "The inline SVG bookshelf illustration has no `aria-hidden` attribute, `role`, or accessible name. Screen readers will attempt to traverse its raw SVG child elements, announcing confusing or meaningless content.",
    fix: "If decorative, add `aria-hidden=\"true\"` and `focusable=\"false\"`. If meaningful, add `role=\"img\"` and an `aria-label` or `<title>` child.",
    fixCode: "<!-- Before -->\n<svg width=\"120\" height=\"80\" viewBox=\"0 0 120 80\" xmlns=\"http://www.w3.org/2000/svg\">\n\n<!-- After (decorative) -->\n<svg width=\"120\" height=\"80\" viewBox=\"0 0 120 80\"\n     xmlns=\"http://www.w3.org/2000/svg\"\n     aria-hidden=\"true\" focusable=\"false\">",
    effortMinutes: 10,
    status: "Fixed",
    fixSummary: "Added `aria-hidden=\"true\" focusable=\"false\"` to the decorative bookshelf SVG on index.html."
  }, {
    // ─── A11Y-017 ───────────────────────────────────────────────────────────
    id: "A11Y-017",
    pages: ["index.html"],
    file: "sample-app/index.html",
    line: 62,
    element: "<a href=\"book.html\" class=\"card-link\">Click here</a>",
    wcag: "2.4.4",
    level: "A",
    category: "Links & Buttons",
    severity: "Medium",
    affects: ["screen reader users", "users with cognitive disabilities"],
    problem: "The link text 'Click here' conveys no information about the destination or purpose. Screen reader users navigating a list of links out of context encounter multiple ambiguous references with no way to distinguish them.",
    fix: "Replace the generic text with a descriptive label that names the specific event and action.",
    fixCode: "<!-- Before -->\n<a href=\"book.html\" class=\"card-link\">Click here</a>\n\n<!-- After -->\n<a href=\"book.html\" class=\"card-link\">Book a seat — Author Talk: Jane Morris</a>",
    effortMinutes: 5,
    status: "Fixed",
    fixSummary: "Replaced 'Click here' with 'Book a seat — Author Talk: Jane Morris' for a descriptive link."
  }, {
    // ─── A11Y-018 ───────────────────────────────────────────────────────────
    id: "A11Y-018",
    pages: ["index.html"],
    file: "sample-app/index.html",
    line: 68,
    element: "<a href=\"book.html\" class=\"card-link\">Read more</a>",
    wcag: "2.4.4",
    level: "A",
    category: "Links & Buttons",
    severity: "Medium",
    affects: ["screen reader users", "users with cognitive disabilities"],
    problem: "'Read more' is a non-descriptive link label that lacks context when a screen reader user navigates by links. Users cannot determine what they will read more about without reading surrounding visual text.",
    fix: "Replace with a descriptive label identifying the specific event.",
    fixCode: "<!-- Before -->\n<a href=\"book.html\" class=\"card-link\">Read more</a>\n\n<!-- After -->\n<a href=\"book.html\" class=\"card-link\">Book a seat — Coding for Beginners</a>",
    effortMinutes: 5,
    status: "Fixed",
    fixSummary: "Replaced 'Read more' with 'Book a seat — Coding for Beginners' for a descriptive link."
  }, {
    // ─── A11Y-019 ───────────────────────────────────────────────────────────
    id: "A11Y-019",
    pages: ["index.html"],
    file: "sample-app/index.html",
    line: 25,
    element: ".hero-slide h1 (three instances)",
    wcag: "1.3.1",
    level: "A",
    category: "Structure",
    severity: "Medium",
    affects: ["screen reader users"],
    problem: "All three carousel slides are present in the DOM simultaneously, each containing an `<h1>` heading. Screen readers encounter three `<h1>` elements on one page, implying three equal top-level topics and producing a confusing document outline.",
    fix: "Use JavaScript to add `aria-hidden=\"true\"` to the non-current slides so only the active slide's `<h1>` is exposed to assistive technology at any time.",
    fixCode: "// In show(), hide non-active slides from assistive technology\nslides.forEach(function (s, i) {\n  s.setAttribute('aria-hidden', i !== current ? 'true' : 'false');\n});",
    effortMinutes: 15,
    status: "Fixed",
    fixSummary: "Non-active slides now get `aria-hidden=\"true\"` set by JS in `show()`, exposing only the current slide's `<h1>` to screen readers; initial HTML sets slides 2 and 3 to `aria-hidden=\"true\"`."
  }, {
    // ─── A11Y-020 ───────────────────────────────────────────────────────────
    id: "A11Y-020",
    pages: ["book.html"],
    file: "sample-app/book.html",
    line: 26,
    element: "<form id=\"booking-form\"> required inputs",
    wcag: "3.3.2",
    level: "A",
    category: "Forms",
    severity: "Medium",
    affects: ["screen reader users", "users with cognitive disabilities"],
    problem: "Required fields have no visible indicator such as an asterisk or the word 'required' before the user attempts to submit. Users have no way to know which fields are mandatory until they accidentally submit an incomplete form.",
    fix: "Add a visible required indicator (asterisk with a legend) to each required field's label.",
    fixCode: "<!-- Add above the form -->\n<p><span aria-hidden=\"true\">*</span> indicates a required field</p>\n\n<!-- Add to each required field label -->\n<label for=\"email\">Email address <span aria-hidden=\"true\" class=\"required-mark\">*</span></label>",
    effortMinutes: 15,
    status: "Fixed",
    fixSummary: "Added a legend paragraph and asterisk `<span aria-hidden=\"true\" class=\"required-mark\">*</span>` to all required field labels on book.html."
  }, {
    // ─── A11Y-021 ───────────────────────────────────────────────────────────
    id: "A11Y-021",
    pages: ["book.html"],
    file: "sample-app/book.html",
    line: 83,
    element: "<button id=\"modal-close-btn\" class=\"modal-close\">",
    wcag: "4.1.2",
    level: "A",
    category: "Links & Buttons",
    severity: "Medium",
    affects: ["screen reader users"],
    problem: "The close button inside the confirmation modal uses the Unicode multiplication sign (✕) as its only label. Screen readers may announce this as 'multiplication x' or 'times' rather than 'close', leaving the user unsure of the button's purpose.",
    fix: "Add `aria-label=\"Close dialog\"` to the button so screen readers announce a meaningful label while the visual ✕ symbol remains.",
    fixCode: "<!-- Before -->\n<button id=\"modal-close-btn\" class=\"modal-close\">&#x2715;</button>\n\n<!-- After -->\n<button id=\"modal-close-btn\" class=\"modal-close\" aria-label=\"Close dialog\">&#x2715;</button>",
    effortMinutes: 2,
    status: "Fixed",
    fixSummary: "Added `aria-label=\"Close dialog\"` to the modal close button on book.html."
  }, {
    // ─── A11Y-022 ───────────────────────────────────────────────────────────
    id: "A11Y-022",
    pages: ["contact.html"],
    file: "sample-app/contact.html",
    line: 27,
    element: "<table class=\"hours-table\">",
    wcag: "1.3.1",
    level: "A",
    category: "Structure",
    severity: "Medium",
    affects: ["screen reader users"],
    problem: "The Opening Hours table contains no `<thead>` and no `<th>` elements — all cells are `<td>`. Screen readers cannot announce column context ('Day' or 'Hours') when reading cell values, so users hear raw data without knowing what the columns represent.",
    fix: "Add a `<thead>` with `<th scope=\"col\">` cells for 'Day' and 'Hours'.",
    fixCode: "<!-- Before -->\n<table class=\"hours-table\">\n  <tbody>\n    <tr>\n      <td>Monday – Friday</td>\n      <td>9:00 am – 7:00 pm</td>\n    </tr>\n\n<!-- After -->\n<table class=\"hours-table\">\n  <thead>\n    <tr>\n      <th scope=\"col\">Day</th>\n      <th scope=\"col\">Hours</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>Monday – Friday</td>\n      <td>9:00 am – 7:00 pm</td>\n    </tr>",
    effortMinutes: 10,
    status: "Fixed",
    fixSummary: "Added `<thead>` with two `<th scope=\"col\">` headers ('Day' and 'Hours') to the Opening Hours table on contact.html."
  }, {
    // ─── A11Y-023 ───────────────────────────────────────────────────────────
    id: "A11Y-023",
    pages: ["contact.html"],
    file: "sample-app/contact.html",
    line: 50,
    element: "<svg width=\"400\" height=\"220\"> (map)",
    wcag: "1.1.1",
    level: "A",
    category: "Images",
    severity: "Medium",
    affects: ["screen reader users"],
    problem: "The SVG map illustration showing the library location has no `role`, `aria-label`, or `<title>` element. Screen readers either ignore it or traverse its raw child elements, providing no meaningful description of the map or the library's location.",
    fix: "Add `role=\"img\"`, a `<title>` child element describing the map, and `aria-labelledby` referencing that title.",
    fixCode: "<!-- Before -->\n<svg width=\"400\" height=\"220\" viewBox=\"0 0 400 220\" xmlns=\"http://www.w3.org/2000/svg\">\n\n<!-- After -->\n<svg role=\"img\" aria-labelledby=\"map-title\"\n     width=\"400\" height=\"220\" viewBox=\"0 0 400 220\"\n     xmlns=\"http://www.w3.org/2000/svg\">\n  <title id=\"map-title\">Map showing the library at the corner of River Road and Mill Street</title>",
    effortMinutes: 10,
    status: "Fixed",
    fixSummary: "Added `role=\"img\"`, `aria-labelledby=\"map-title\"`, and a `<title>` child to the SVG map on contact.html."
  }, {
    // ─── A11Y-024 ───────────────────────────────────────────────────────────
    id: "A11Y-024",
    pages: ["contact.html"],
    file: "sample-app/contact.html",
    line: 71,
    element: "<a href=\"tel:+441234567890\" style=\"color:#1a1a2e;text-decoration:none;\">",
    wcag: "1.4.1",
    level: "A",
    category: "Links & Buttons",
    severity: "Medium",
    affects: ["color-blind users", "low-vision users"],
    problem: "The phone number link has `text-decoration: none` and `color: #1a1a2e` — the same colour as the surrounding body text. There is no underline, border, icon, or any other visual cue that identifies it as a link.",
    fix: "Remove the `text-decoration: none` inline style so the link is visually distinguished from surrounding text.",
    fixCode: "<!-- Before -->\n<a href=\"tel:+441234567890\" style=\"color:#1a1a2e;text-decoration:none;\">01234 567890</a>\n\n<!-- After -->\n<a href=\"tel:+441234567890\" style=\"color:#1a1a2e;\">01234 567890</a>",
    effortMinutes: 5,
    status: "Fixed",
    fixSummary: "Removed `text-decoration:none` from the phone link on contact.html so it is underlined by default."
  }, {
    // ─── A11Y-025 ───────────────────────────────────────────────────────────
    id: "A11Y-025",
    pages: ["contact.html"],
    file: "sample-app/contact.html",
    line: 85,
    element: "<button class=\"faq-toggle\">",
    wcag: "4.1.2",
    level: "A",
    category: "ARIA & Dynamic",
    severity: "Medium",
    affects: ["screen reader users"],
    problem: "The FAQ accordion toggle buttons do not have `aria-expanded` and the JavaScript never sets it. Screen reader users are not informed whether an answer panel is currently open or closed.",
    fix: "Add `aria-expanded=\"false\"` to each `.faq-toggle` button in the HTML, and update `initFaq()` to toggle the attribute between 'true' and 'false' when the button is clicked.",
    fixCode: "<!-- Before -->\n<button class=\"faq-toggle\">Is library membership free?</button>\n\n<!-- After -->\n<button class=\"faq-toggle\" aria-expanded=\"false\" aria-controls=\"faq-1\">Is library membership free?</button>\n<div class=\"faq-body\" id=\"faq-1\">...</div>\n\n// app.js\nbtn.addEventListener('click', function () {\n  var body = btn.nextElementSibling;\n  if (!body) return;\n  var isOpen = body.classList.toggle('open');\n  btn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');\n});",
    effortMinutes: 15,
    status: "Fixed",
    fixSummary: "Added `aria-expanded=\"false\"` to all FAQ toggle buttons in HTML; JS now updates `aria-expanded` to `true`/`false` on each click."
  }, {
    // ─── A11Y-026 ───────────────────────────────────────────────────────────
    id: "A11Y-026",
    pages: ["contact.html"],
    file: "sample-app/contact.html",
    line: 86,
    element: "<div class=\"faq-body\">",
    wcag: "4.1.2",
    level: "A",
    category: "ARIA & Dynamic",
    severity: "Medium",
    affects: ["screen reader users"],
    problem: "The FAQ answer panels have no `id` attributes, and the toggle buttons have no `aria-controls` pointing to them. Screen reader users who activate a button have no programmatic association to the content it controls.",
    fix: "Assign a unique `id` to each `.faq-body` element and add a matching `aria-controls` attribute to the corresponding toggle button.",
    fixCode: "<!-- Before -->\n<button class=\"faq-toggle\">Can I book without being a member?</button>\n<div class=\"faq-body\">...</div>\n\n<!-- After -->\n<button class=\"faq-toggle\" aria-expanded=\"false\" aria-controls=\"faq-2\">Can I book without being a member?</button>\n<div class=\"faq-body\" id=\"faq-2\">...</div>",
    effortMinutes: 10,
    status: "Fixed",
    fixSummary: "Added `id=\"faq-1\"` through `faq-4` to FAQ body panels and matching `aria-controls` to each toggle button on contact.html."
  }, {
    // ─── A11Y-027 ───────────────────────────────────────────────────────────
    id: "A11Y-027",
    pages: ["index.html"],
    file: "sample-app/styles.css",
    line: 91,
    element: ".hero-dot",
    wcag: "2.5.8",
    level: "AA",
    category: "Mobile & Zoom",
    severity: "Medium",
    affects: ["mobile and zoom users"],
    problem: "Each carousel dot is 10×10 CSS pixels, well below the WCAG 2.2 minimum touch target size of 24×24 px. Users with motor impairments or on touch screens will have difficulty accurately tapping such small targets.",
    fix: "Increase the dot's effective interactive area to at least 24×24 px using padding, while keeping the visual dot size unchanged via `background-clip`.",
    fixCode: "/* Before */\n.hero-dot {\n  width: 10px;\n  height: 10px;\n  border-radius: 50%;\n  background: rgba(255,255,255,0.4);\n  cursor: pointer;\n  display: inline-block;\n}\n\n/* After */\n.hero-dot {\n  width: 10px;\n  height: 10px;\n  border-radius: 50%;\n  background: rgba(255,255,255,0.4);\n  background-clip: content-box;\n  padding: 7px;\n  cursor: pointer;\n  display: inline-block;\n}",
    effortMinutes: 10,
    status: "Fixed",
    fixSummary: "Added `padding: 7px` and `background-clip: content-box` to `.hero-dot` so the interactive area is 24×24 px while the visual dot remains 10×10 px."
  }, {
    // ─── A11Y-028 ───────────────────────────────────────────────────────────
    id: "A11Y-028",
    pages: ["index.html", "book.html", "contact.html"],
    file: "sample-app/index.html",
    line: 6,
    element: "<title>",
    wcag: "2.4.2",
    level: "A",
    category: "Page",
    severity: "Low",
    affects: ["screen reader users", "users with cognitive disabilities"],
    problem: "All three pages share the identical `<title>Riverside Community Library</title>`. Screen reader users cannot distinguish which page they are on by title alone, and browser history and tab titles provide no page-specific context.",
    fix: "Prepend a unique page name to each title using the 'Page — Site' pattern.",
    fixCode: "<!-- index.html -->\n<title>Home — Riverside Community Library</title>\n\n<!-- book.html -->\n<title>Book an Event — Riverside Community Library</title>\n\n<!-- contact.html -->\n<title>Contact &amp; Visit Us — Riverside Community Library</title>",
    effortMinutes: 5,
    status: "Fixed",
    fixSummary: "Updated `<title>` on all three pages to use unique 'Page — Site' pattern (one-line change per page)."
  }, {
    // ─── A11Y-029 ───────────────────────────────────────────────────────────
    id: "A11Y-029",
    pages: ["index.html"],
    file: "sample-app/index.html",
    line: 57,
    element: "<div class=\"cards\">",
    wcag: "1.3.1",
    level: "A",
    category: "Structure",
    severity: "Low",
    affects: ["screen reader users"],
    problem: "The three event cards are plain `<div>` elements with no semantic grouping. Screen reader users receive no structural cue that these items form a related list of events, and no count of how many items are present.",
    fix: "Wrap the card container in a `<ul>` and make each card an `<li>`. Apply `list-style: none` in CSS to preserve the visual layout.",
    fixCode: "<!-- Before -->\n<div class=\"cards\">\n  <div class=\"card\">...</div>\n\n<!-- After -->\n<ul class=\"cards\" style=\"list-style:none;padding:0;\">\n  <li class=\"card\">...</li>",
    effortMinutes: 10,
    status: "Open",
    fixSummary: "Low severity; converting the cards to a <ul>/<li> list requires structural changes to more than one line per card element and was deferred."
  } ]
};
