window.A11Y_FINDINGS = {
  project: "Riverside Community Library Sample App",
  standard: "WCAG 2.2 AA",
  generatedAt: "2025-07-14",
  findings: [
    {
      id: "A11Y-001",
      pages: ["index.html", "book.html", "contact.html"],
      file: "sample-app/styles.css",
      line: 8,
      element: "* { outline: none; }",
      wcag: "2.4.7",
      level: "AA",
      category: "Keyboard & Focus",
      severity: "High",
      affects: ["keyboard-only users", "low-vision users"],
      problem: "The universal CSS rule `* { outline: none; }` removes the browser-default focus ring from every focusable element across all three pages. Keyboard-only users have no visual cue showing where focus is, making the entire site effectively unusable without a mouse.",
      fix: "Remove the `outline: none` wildcard rule. Replace with a `:focus-visible` style that provides a clearly visible high-contrast focus ring.",
      fixCode: "/* Before */\n* {\n  outline: none;\n}\n\n/* After */\n:focus-visible {\n  outline: 2px solid #0f3460;\n  outline-offset: 2px;\n}",
      effortMinutes: 10,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-002",
      pages: ["index.html", "book.html", "contact.html"],
      file: "sample-app/index.html",
      line: 5,
      element: "<meta name=\"viewport\" content=\"…user-scalable=no, maximum-scale=1.0\">",
      wcag: "1.4.4",
      level: "AA",
      category: "Mobile & Zoom",
      severity: "High",
      affects: ["low-vision users", "mobile and zoom users"],
      problem: "All three pages include `user-scalable=no, maximum-scale=1.0` in the viewport meta tag, preventing users from pinching to zoom or using browser text-scaling. Low-vision users who rely on 200–400% zoom to read content are completely blocked.",
      fix: "Remove `user-scalable=no` and `maximum-scale=1.0` from the viewport meta tag on all three pages.",
      fixCode: "<!-- Before -->\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no, maximum-scale=1.0\">\n\n<!-- After -->\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">",
      effortMinutes: 5,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-003",
      pages: ["index.html"],
      file: "sample-app/app.js",
      line: 19,
      element: "setInterval(function () { show(current + 1); }, 3000)",
      wcag: "2.2.2",
      level: "A",
      category: "Motion",
      severity: "High",
      affects: ["users with cognitive disabilities", "keyboard-only users", "screen reader users"],
      problem: "The hero banner automatically rotates slides every three seconds with no button or mechanism to pause, stop, or hide the movement. Users with attention or cognitive disabilities can be distracted by constant motion, and screen reader users may be disrupted as content changes beneath them.",
      fix: "Add a visible pause/play button next to the carousel dots. Clear the setInterval when paused. Also skip auto-rotation when `prefers-reduced-motion: reduce` is set.",
      fixCode: "<!-- Before: no pause control -->\n<div class=\"hero-dots\">\n  <span class=\"hero-dot active\"></span>\n  <span class=\"hero-dot\"></span>\n  <span class=\"hero-dot\"></span>\n</div>\n\n<!-- After -->\n<div class=\"hero-dots\">\n  <span class=\"hero-dot active\"></span>\n  <span class=\"hero-dot\"></span>\n  <span class=\"hero-dot\"></span>\n  <button class=\"hero-pause\" aria-label=\"Pause slideshow\">&#9646;&#9646;</button>\n</div>",
      effortMinutes: 30,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-004",
      pages: ["index.html"],
      file: "sample-app/index.html",
      line: 47,
      element: "<svg width=\"120\" height=\"80\"> (library skyline illustration)",
      wcag: "1.1.1",
      level: "A",
      category: "Images",
      severity: "High",
      affects: ["screen reader users"],
      problem: "The SVG illustration of the library skyline conveys visual context but has no `<title>`, `aria-label`, or `role=\"img\"`. Screen readers will either announce raw SVG markup or skip it silently, providing no meaningful description.",
      fix: "Add `role=\"img\"` and `aria-label` to the `<svg>`, or add a `<title>` as its first child. If the image is purely decorative, add `aria-hidden=\"true\"` instead.",
      fixCode: "<!-- Before -->\n<svg width=\"120\" height=\"80\" viewBox=\"0 0 120 80\" xmlns=\"http://www.w3.org/2000/svg\">\n\n<!-- After (informative) -->\n<svg width=\"120\" height=\"80\" viewBox=\"0 0 120 80\" xmlns=\"http://www.w3.org/2000/svg\"\n     role=\"img\" aria-label=\"Illustration of the Riverside Library building\">\n  <title>Riverside Library building illustration</title>",
      effortMinutes: 5,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-005",
      pages: ["index.html"],
      file: "sample-app/index.html",
      line: 80,
      element: "<div id=\"newsletter-action\">",
      wcag: "2.1.1",
      level: "A",
      category: "Keyboard & Focus",
      severity: "High",
      affects: ["keyboard-only users", "screen reader users"],
      problem: "The \"Sign up for our newsletter\" control is a plain `<div>` with only a click event handler and no `role`, `tabindex`, or keyboard event handler. Keyboard-only users cannot reach or activate it because `<div>` elements are not focusable or operable by keyboard.",
      fix: "Replace the `<div>` with a `<button>` element. The existing JavaScript click handler will continue to work without modification.",
      fixCode: "<!-- Before -->\n<div id=\"newsletter-action\"\n     style=\"display:inline-block;background:#0f3460;color:#fff;padding:0.75rem 2rem;border-radius:4px;cursor:pointer;font-size:1rem;\">\n  Sign up for our newsletter\n</div>\n\n<!-- After -->\n<button id=\"newsletter-action\"\n        style=\"display:inline-block;background:#0f3460;color:#fff;padding:0.75rem 2rem;border-radius:4px;cursor:pointer;font-size:1rem;border:none;\">\n  Sign up for our newsletter\n</button>",
      effortMinutes: 10,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-006",
      pages: ["index.html"],
      file: "sample-app/styles.css",
      line: 79,
      element: ".hero p",
      wcag: "1.4.3",
      level: "AA",
      category: "Color & Contrast",
      severity: "High",
      affects: ["low-vision users", "color-blind users"],
      problem: "Hero paragraph text uses colour `#a8a8b3` on a `#0f3460` background, producing a contrast ratio of approximately 2.8:1. The WCAG 2.2 AA minimum for normal text is 4.5:1, so low-vision users will struggle to read the event sub-descriptions.",
      fix: "Change `.hero p` colour to `#ffffff` (or another value achieving at least 4.5:1 contrast against `#0f3460`). White yields approximately 14:1 and matches the h1 heading already used in the hero.",
      fixCode: "/* Before */\n.hero p {\n  color: #a8a8b3;\n}\n\n/* After */\n.hero p {\n  color: #ffffff;\n}",
      effortMinutes: 5,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-007",
      pages: ["book.html"],
      file: "sample-app/book.html",
      line: 29,
      element: "<input type=\"email\" id=\"email\">",
      wcag: "1.3.1",
      level: "A",
      category: "Forms",
      severity: "High",
      affects: ["screen reader users", "users with cognitive disabilities"],
      problem: "The email input field uses only `placeholder=\"Your email address\"` as its label. Placeholders disappear when the user starts typing, leaving users with no persistent reminder of the field's purpose, and screen readers may not reliably expose placeholder text as a programmatic label.",
      fix: "Add a `<label for=\"email\">Email address</label>` element above the input. The placeholder may remain as a supplementary hint.",
      fixCode: "<!-- Before -->\n<div class=\"form-group\">\n  <input type=\"email\" id=\"email\" name=\"email\"\n         placeholder=\"Your email address\"\n         required autocomplete=\"email\">\n</div>\n\n<!-- After -->\n<div class=\"form-group\">\n  <label for=\"email\">Email address</label>\n  <input type=\"email\" id=\"email\" name=\"email\"\n         placeholder=\"Your email address\"\n         required autocomplete=\"email\">\n</div>",
      effortMinutes: 5,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-008",
      pages: ["book.html"],
      file: "sample-app/book.html",
      line: 71,
      element: "<button type=\"submit\" class=\"btn-primary\">",
      wcag: "4.1.2",
      level: "A",
      category: "Links & Buttons",
      severity: "High",
      affects: ["screen reader users"],
      problem: "The booking form's submit button contains only an SVG checkmark with `aria-hidden=\"true\"`, giving the button no accessible name at all. Screen readers announce it as an unlabelled button, and voice-control users cannot activate it by speaking its name.",
      fix: "Add visible text inside the button (e.g. \"Confirm booking\"), or add `aria-label=\"Submit booking\"` to the button element.",
      fixCode: "<!-- Before -->\n<button type=\"submit\" class=\"btn-primary\" style=\"display:flex;align-items:center;gap:0.5rem;\">\n  <svg width=\"18\" height=\"18\" aria-hidden=\"true\" focusable=\"false\">...</svg>\n</button>\n\n<!-- After -->\n<button type=\"submit\" class=\"btn-primary\" style=\"display:flex;align-items:center;gap:0.5rem;\">\n  <svg width=\"18\" height=\"18\" aria-hidden=\"true\" focusable=\"false\">...</svg>\n  Confirm booking\n</button>",
      effortMinutes: 5,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-009",
      pages: ["book.html"],
      file: "sample-app/app.js",
      line: 33,
      element: "field.classList.add('error')",
      wcag: "3.3.1",
      level: "A",
      category: "Forms",
      severity: "High",
      affects: ["screen reader users", "color-blind users", "users with cognitive disabilities"],
      problem: "When form validation fails, JavaScript adds only a red border to the offending fields with no error message text, no `aria-describedby` link, and no live region announcement. Screen reader users and colour-blind users receive no indication that validation has failed.",
      fix: "Inject a text error message below each invalid field, set `aria-describedby` on the input to reference that message, and wrap error messages in an `aria-live=\"assertive\"` or `role=\"alert\"` container.",
      fixCode: "// Before\nfield.classList.add('error');\n\n// After\nfield.classList.add('error');\nvar errId = field.id + '-error';\nvar errEl = document.getElementById(errId);\nif (!errEl) {\n  errEl = document.createElement('span');\n  errEl.id = errId;\n  errEl.className = 'field-error';\n  field.parentNode.appendChild(errEl);\n}\nerrEl.textContent = field.labels[0]\n  ? field.labels[0].textContent + ' is required.'\n  : 'This field is required.';\nfield.setAttribute('aria-describedby', errId);",
      effortMinutes: 30,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-010",
      pages: ["book.html"],
      file: "sample-app/app.js",
      line: 53,
      element: "#confirmation-modal / showConfirmationModal()",
      wcag: "2.1.1",
      level: "A",
      category: "Keyboard & Focus",
      severity: "High",
      affects: ["keyboard-only users", "screen reader users"],
      problem: "When the booking confirmation modal opens, focus remains on the submit button behind the backdrop and keyboard users cannot reach the close button. Pressing Escape does not close the modal, and focus is not returned to the triggering element on close.",
      fix: "On modal open, move focus to the close button. Add a keydown listener to close the modal on Escape. On close, return focus to the submit button. Add `aria-modal=\"true\"` to the dialog element.",
      fixCode: "// Before\nfunction showConfirmationModal() {\n  var backdrop = document.getElementById('confirmation-modal');\n  backdrop.classList.add('open');\n  document.getElementById('modal-close-btn').addEventListener('click', function () {\n    backdrop.classList.remove('open');\n  });\n}\n\n// After\nfunction showConfirmationModal() {\n  var backdrop = document.getElementById('confirmation-modal');\n  var closeBtn = document.getElementById('modal-close-btn');\n  var submitBtn = document.querySelector('#booking-form [type=\"submit\"]');\n  backdrop.setAttribute('aria-modal', 'true');\n  backdrop.classList.add('open');\n  closeBtn.focus();\n  function handleEscape(e) { if (e.key === 'Escape') closeModal(); }\n  function closeModal() {\n    backdrop.classList.remove('open');\n    document.removeEventListener('keydown', handleEscape);\n    if (submitBtn) submitBtn.focus();\n  }\n  closeBtn.addEventListener('click', closeModal, { once: true });\n  document.addEventListener('keydown', handleEscape);\n}",
      effortMinutes: 30,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-011",
      pages: ["contact.html"],
      file: "sample-app/contact.html",
      line: 50,
      element: "<svg width=\"400\" height=\"220\"> (location map)",
      wcag: "1.1.1",
      level: "A",
      category: "Images",
      severity: "High",
      affects: ["screen reader users"],
      problem: "The SVG map showing the library location conveys meaningful spatial information but has no `role=\"img\"`, `aria-label`, or `<title>`. Screen reader users receive no description and cannot use the map to orientate themselves.",
      fix: "Add `role=\"img\"` and `aria-label` to the `<svg>` describing the map content, or add a `<title>` element as its first child.",
      fixCode: "<!-- Before -->\n<svg width=\"400\" height=\"220\" viewBox=\"0 0 400 220\"\n     xmlns=\"http://www.w3.org/2000/svg\"\n     style=\"border:1px solid #e5e7eb;...\">\n\n<!-- After -->\n<svg width=\"400\" height=\"220\" viewBox=\"0 0 400 220\"\n     xmlns=\"http://www.w3.org/2000/svg\"\n     role=\"img\"\n     aria-label=\"Map showing the library at 42 River Road at the corner of River Road and Mill Street\"\n     style=\"border:1px solid #e5e7eb;...\">\n  <title>Map: Riverside Library location at 42 River Road</title>",
      effortMinutes: 5,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-012",
      pages: ["index.html", "book.html", "contact.html"],
      file: "sample-app/index.html",
      line: 6,
      element: "<title>Riverside Community Library</title>",
      wcag: "2.4.2",
      level: "A",
      category: "Page",
      severity: "Medium",
      affects: ["screen reader users", "users with cognitive disabilities"],
      problem: "All three pages share the identical `<title>Riverside Community Library</title>`. Screen reader users with multiple tabs open cannot distinguish which tab is which, and browser history provides no page-level context.",
      fix: "Give each page a unique, descriptive title following the pattern \"Page Name — Site Name\".",
      fixCode: "<!-- Before (all three pages) -->\n<title>Riverside Community Library</title>\n\n<!-- After -->\n<!-- index.html   --> <title>Home — Riverside Community Library</title>\n<!-- book.html    --> <title>Book an Event — Riverside Community Library</title>\n<!-- contact.html --> <title>Contact &amp; Visit Us — Riverside Community Library</title>",
      effortMinutes: 5,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-013",
      pages: ["index.html", "book.html", "contact.html"],
      file: "sample-app/index.html",
      line: 11,
      element: "<header class=\"site-header\">",
      wcag: "2.4.1",
      level: "A",
      category: "Keyboard & Focus",
      severity: "Medium",
      affects: ["keyboard-only users", "screen reader users"],
      problem: "None of the three pages provide a skip-navigation link. Keyboard users must tab through the site header and all navigation links on every page before reaching the main content.",
      fix: "Add a visually hidden \"Skip to main content\" link as the first element in `<body>` on each page. Use the existing `.visually-hidden` class and reveal it on focus.",
      fixCode: "<!-- Before: first element is <header> -->\n<body>\n  <header class=\"site-header\">\n\n<!-- After -->\n<body>\n  <a href=\"#main\" class=\"skip-link visually-hidden\">Skip to main content</a>\n  <header class=\"site-header\">",
      effortMinutes: 15,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-014",
      pages: ["index.html"],
      file: "sample-app/index.html",
      line: 55,
      element: "<h3 class=\"section-title\">Upcoming Events</h3>",
      wcag: "1.3.1",
      level: "A",
      category: "Structure",
      severity: "Medium",
      affects: ["screen reader users", "users with cognitive disabilities"],
      problem: "The page heading hierarchy jumps from `<h1>` in the hero section directly to `<h3>` for the \"Upcoming Events\" section title, skipping `<h2>`. Screen reader users who navigate by headings find a gap in the document outline suggesting a missing section.",
      fix: "Change the \"Upcoming Events\" heading to `<h2>`. Event card headings that are currently `<h3>` remain correct within that context.",
      fixCode: "<!-- Before -->\n<h3 class=\"section-title\">Upcoming Events</h3>\n\n<!-- After -->\n<h2 class=\"section-title\">Upcoming Events</h2>",
      effortMinutes: 5,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-015",
      pages: ["index.html"],
      file: "sample-app/index.html",
      line: 62,
      element: "<a href=\"book.html\" class=\"card-link\">Click here</a>",
      wcag: "2.4.4",
      level: "A",
      category: "Links & Buttons",
      severity: "Medium",
      affects: ["screen reader users", "users with cognitive disabilities"],
      problem: "Two event card links use the text \"Click here\" and \"Read more\". When screen reader users browse a list of links out of context, they hear only the generic text with no indication of which event is being referenced.",
      fix: "Rewrite the link text to describe the destination, or add `aria-label` with an event-specific name.",
      fixCode: "<!-- Before -->\n<a href=\"book.html\" class=\"card-link\">Click here</a>\n<a href=\"book.html\" class=\"card-link\">Read more</a>\n\n<!-- After -->\n<a href=\"book.html\" class=\"card-link\">Book a seat — Author Talk: Jane Morris</a>\n<a href=\"book.html\" class=\"card-link\">Book a seat — Coding for Beginners</a>",
      effortMinutes: 10,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-016",
      pages: ["index.html"],
      file: "sample-app/styles.css",
      line: 91,
      element: ".hero-dot",
      wcag: "2.5.8",
      level: "AA",
      category: "Keyboard & Focus",
      severity: "Medium",
      affects: ["mobile and zoom users", "keyboard-only users"],
      problem: "The carousel navigation dots are styled at `width: 10px; height: 10px`, well below the WCAG 2.2 AA minimum of 24×24 CSS pixels. Users with motor impairments or on touch screens will find them very difficult to tap accurately.",
      fix: "Increase the total tap target to at least 24×24 px using padding. Also replace the `<span>` elements with `<button>` elements so dots are keyboard-operable.",
      fixCode: "/* Before */\n.hero-dot {\n  width: 10px;\n  height: 10px;\n}\n\n/* After */\n.hero-dot {\n  width: 12px;\n  height: 12px;\n  padding: 6px;\n  box-sizing: content-box;\n}",
      effortMinutes: 10,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-017",
      pages: ["book.html"],
      file: "sample-app/book.html",
      line: 2,
      element: "<html>",
      wcag: "3.1.1",
      level: "A",
      category: "Structure",
      severity: "Medium",
      affects: ["screen reader users"],
      problem: "The `<html>` element on book.html has no `lang` attribute. Screen readers will apply their default language setting, which may cause text to be pronounced incorrectly for users configured for a different language.",
      fix: "Add `lang=\"en\"` to the `<html>` element on book.html, matching the other two pages.",
      fixCode: "<!-- Before -->\n<html>\n\n<!-- After -->\n<html lang=\"en\">",
      effortMinutes: 2,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-018",
      pages: ["contact.html"],
      file: "sample-app/contact.html",
      line: 27,
      element: ".hours-table",
      wcag: "1.3.1",
      level: "A",
      category: "Forms",
      severity: "Medium",
      affects: ["screen reader users"],
      problem: "The opening hours table uses `<td>` for all cells including column headings, so screen readers cannot identify column headers and users navigating the table hear values with no structural context.",
      fix: "Add a `<thead>` with `<th scope=\"col\">` elements for the column headers, or change the first-column cells to `<th scope=\"row\">`.",
      fixCode: "<!-- Before -->\n<table class=\"hours-table\">\n  <tbody>\n    <tr><td>Monday – Friday</td><td>9:00 am – 7:00 pm</td></tr>\n\n<!-- After -->\n<table class=\"hours-table\">\n  <thead>\n    <tr>\n      <th scope=\"col\">Day</th>\n      <th scope=\"col\">Hours</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr><td>Monday – Friday</td><td>9:00 am – 7:00 pm</td></tr>",
      effortMinutes: 10,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-019",
      pages: ["contact.html"],
      file: "sample-app/app.js",
      line: 64,
      element: ".faq-toggle buttons / initFaq()",
      wcag: "4.1.2",
      level: "A",
      category: "ARIA & Dynamic",
      severity: "Medium",
      affects: ["screen reader users"],
      problem: "The FAQ accordion buttons toggle their answer panels but never update `aria-expanded`. Screen reader users cannot tell whether a panel is currently open or closed without navigating into the content.",
      fix: "Set `aria-expanded=\"false\"` on each `.faq-toggle` in HTML, then toggle it to `\"true\"` and back in the JavaScript click handler.",
      fixCode: "<!-- Before -->\n<button class=\"faq-toggle\">Is library membership free?</button>\n\n<!-- After -->\n<button class=\"faq-toggle\" aria-expanded=\"false\">Is library membership free?</button>\n\n// JS — Before\nbody.classList.toggle('open');\n\n// JS — After\nbody.classList.toggle('open');\nbtn.setAttribute('aria-expanded', body.classList.contains('open') ? 'true' : 'false');",
      effortMinutes: 10,
      status: "Open",
      fixSummary: ""
    },
    {
      id: "A11Y-020",
      pages: ["contact.html"],
      file: "sample-app/contact.html",
      line: 71,
      element: "<a href=\"tel:+441234567890\">",
      wcag: "1.4.1",
      level: "A",
      category: "Color & Contrast",
      severity: "Low",
      affects: ["color-blind users", "low-vision users"],
      problem: "The telephone link is styled with `color:#1a1a2e; text-decoration:none;`, making it visually identical to the surrounding plain text. Users cannot identify it as a link without hovering, which is not possible on touch devices.",
      fix: "Remove `text-decoration:none` from the telephone link so it displays with a standard underline, or add another non-colour visual distinguisher.",
      fixCode: "<!-- Before -->\n<a href=\"tel:+441234567890\" style=\"color:#1a1a2e;text-decoration:none;\">01234 567890</a>\n\n<!-- After -->\n<a href=\"tel:+441234567890\">01234 567890</a>",
      effortMinutes: 5,
      status: "Open",
      fixSummary: ""
    }
  ]
};
